In [2]:
import pandas as pd
import wbdata

In [11]:
# indicadores para descargar
indicadores = {
    "NY.GNP.PCAP.CD": "GNI per capita, Atlas method (current US$)",
    "SP.DYN.TFRT.IN": "Fertility rate, total (births per woman)",
    "SP.DYN.LE00.IN": "Life expectancy at birth, total (years)",
    "SH.DYN.MORT": "Mortality rate, under-5 (per 1,000 live births)",
    "SL.UEM.TOTL.ZS": "Unemployment, total (% of total labor force) (modeled ILO estimate)"
}

# códigos de país de América Latina y el Caribe
paises_latam_caribe = ['ATG', 'ARG', 'BHS', 'BRB', 'BLZ', 'BOL', 'BRA', 'CHL', 'COL',
                       'CRI', 'CUB', 'DMA', 'DOM', 'ECU', 'SLV', 'GRD', 'GTM', 'GUY',
                       'HTI', 'HND', 'JAM', 'MEX', 'NIC', 'PAN', 'PRY', 'PER', 'PRI',
                       'KNA', 'LCA', 'VCT', 'SUR', 'TTO', 'URY', 'VEN']

# Descargar los datos de los indicadores para los países de América Latina y el Caribe
data = wbdata.get_dataframe(indicadores, country=paises_latam_caribe, convert_date=True)


data = data.reset_index()


data["date"] = data["date"].dt.year

df = data

while df[df['date']==df['date'].max()].isnull().sum(axis=1).sum()/len(df[df['date']==df['date'].max()]) > 2:
    df = df[df['date'] != df['date'].max()]

df = df.groupby('country').apply(lambda x: x.nlargest(30, 'date')).reset_index(drop=True)

Aumentar el GNI per capita en al menos un 10% en razón del GNI per capita a nivel regional alcanzado para el 2021 en comparación con el 2016.

In [6]:
df_GNI = df[['date','GNI per capita, Atlas method (current US$)']].groupby('date').mean()
df_GNI['percentage change'] = df_GNI['GNI per capita, Atlas method (current US$)'].pct_change(5)*100
df_GNI.tail(10)

      GNI per capita, Atlas method (current US$)  percentage change
date
2012                                 8957.941176          29.576686
2013                                 9367.352941          22.822105
2014                                 9520.882353          24.907393
2015                                 9380.606061          18.086788
2016                                 9286.666667          11.583089
2017                                 9464.848485           5.658748
2018                                 9939.090909           6.103517
2019                                10237.272727           7.524412
2020                                 9018.750000          -3.857491
2021                                 9701.875000           4.471016

Reducir la tasa de fertilidad en al menos un 8% en razón de la tasa de fertilidad a nivel regional alcanzada para el 2021 en comparación con el 2016.

In [7]:
df_Fertility = df[['date','Fertility rate, total (births per woman)']].groupby('date').mean()
df_Fertility['percentage change'] = df_Fertility['Fertility rate, total (births per woman)'].pct_change(5)*100
df_Fertility.tail(7)

      Fertility rate, total (births per woman)  percentage change
date
2015                                  2.115132          -6.825381
2016                                  2.068250          -7.769741
2017                                  2.026588          -8.171466
2018                                  1.988324          -8.207962
2019                                  1.948294          -9.110617
2020                                  1.916559          -9.388232
2021                                  1.895529          -8.351050

Aumentar la esperanza de vida en al menos un 3%% en razón de la esperanza de vida a nivel regional alcanzada para el 2021 en comparación con el 2011.

In [8]:
df_Life = df[['date','Life expectancy at birth, total (years)']].groupby('date').mean()
df_Life['percentage change'] = df_Life['Life expectancy at birth, total (years)'].pct_change(10)*100
df_Life.tail(11)

      Life expectancy at birth, total (years)  percentage change
date
2011                                73.384029           3.300660
2012                                73.583412           3.069718
2013                                73.691618           3.084281
2014                                73.812412           2.852391
2015                                73.928912           2.530358
2016                                74.084853           2.374306
2017                                74.109618           2.119120
2018                                74.361853           2.103327
2019                                74.340324           1.711154
2020                                73.429382           0.951613
2021                                72.371324          -1.380009

Reducir la tasa de mortalidad infantil en al menos un 10% en razón de la tasa de mortalidad infantil a nivel regional alcanzada para el 2021 en comparación con el 2016.

In [9]:
df_Mortality = df[['date','Mortality rate, under-5 (per 1,000 live births)']].groupby('date').mean()
df_Mortality['percentage change'] = df_Mortality['Mortality rate, under-5 (per 1,000 live births)'].pct_change(5)*100
df_Mortality.tail(7)

      Mortality rate, under-5 (per 1,000 live births)  percentage change
date
2015                                        19.490909         -17.145433
2016                                        19.227273         -10.305344
2017                                        18.757576         -10.250834
2018                                        18.293939         -10.350460
2019                                        18.136364          -9.014898
2020                                        17.363636         -10.914179
2021                                        16.909091         -12.056738

Reducir el porcentaje de desempleo en al menos un 10% en razón del porcentaje de desempleo a nivel regional alcanzado para el 2021 en comparación con el 2020.

In [10]:
df_Unemployment = df[['date','Unemployment, total (% of total labor force) (modeled ILO estimate)']].groupby('date').mean()
df_Unemployment['percentage change'] = df_Unemployment['Unemployment, total (% of total labor force) (modeled ILO estimate)'].pct_change(1)*100
df_Unemployment.tail(7)

,"Unemployment, total (% of total labor force) (modeled ILO estimate)",percentage change
date,,
2015,7.666867,-2.444342
2016,7.820400,2.002556
2017,7.515067,-3.904319
2018,7.610133,1.265014
2019,7.652500,0.556714
2020,10.006267,30.758140
2021,9.059400,-9.462737